language: csharp

env:
  - HOME=/home/travis APPDATA=/home/travis LocalAppData=/home/travis

sudo: required #false
dist: bionic
dotnet: 3.1.101
mono:
  - 6.10.0
os:
  - linux

branches:
  except:
    - gh-pages

script:
  - ./build.sh Test quick
global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
